/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.UsuarioControl;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Paola
 */
public class FormGestionarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FormGestionarUsuario
     */
    UsuarioControl usuarioControl;
    
    public FormGestionarUsuario() {
        initComponents();
        this.usuarioControl = new UsuarioControl();
        ArrayList<String> empleados = this.usuarioControl.todosEmpleados();
        System.out.println("Tamaño "+empleados.size());
        cbEmpleado.removeAllItems();
        for (String empleado : empleados) {
            cbEmpleado.addItem(empleado);
        }
        
        ArrayList<String> nivelaccesos = this.usuarioControl.todosNivelAcceso();
        cbNivelAcceso.removeAllItems();
        for (String nivelacceso: nivelaccesos){
            cbNivelAcceso.addItem(nivelacceso);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo1 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblNivelAcceso = new javax.swing.JLabel();
        cbEmpleado = new javax.swing.JComboBox<>();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        cbNivelAcceso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo1.setText("Permitir acceso a un nuevo usuario");

        lblEmpleado.setText("Empleado:");

        lblUsuario.setText("Usuario:");

        lblContraseña.setText("Contraseña:");

        lblNivelAcceso.setText("Nivel acceso:");

        cbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar empleado", "Item 2", "Item 3", "Item 4" }));

        cbNivelAcceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija el nivel de acceso", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña)
                            .addComponent(lblNivelAcceso)
                            .addComponent(lblUsuario)
                            .addComponent(lblEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbNivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1)
                        .addGap(96, 96, 96)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpleado)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelAcceso)
                    .addComponent(cbNivelAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String mensajeError = "";
        
        if(txtUsuario.getText().equals("")){
            mensajeError += "Campo de usuario vacio.\n";
        }
        
        if(txtContraseña.getText().equals("")){
            mensajeError += "Campo de contraseña vacio.\n";
        }
        
        if(mensajeError.equals("")){
            int codEmpleado = 0;
            for (int i = 0; i < cbEmpleado.getSelectedItem().toString().length(); i++) {
                if(cbEmpleado.getSelectedItem().toString().charAt(i) == '.'){
                    codEmpleado = Integer.parseInt(cbEmpleado.getSelectedItem().toString().substring(0, i));
                }
            }
            
            usuarioControl.obtenerEmpleado(codEmpleado);
            String usuario = this.txtUsuario.getText();
            String contraseña = this.txtContraseña.getText();
            int nivel = Integer.parseInt(this.cbNivelAcceso.getSelectedItem().toString());
            String nombre = usuarioControl.getEmp().getNombreEmpleado();
            String apellido = usuarioControl.getEmp().getApellidoEmpleado();
            int puesto = usuarioControl.getEmp().getPuesto().getCodPuesto();
            
            usuarioControl.crearUsuario(usuario, contraseña, nivel, codEmpleado, nombre, apellido, puesto);
            
            JOptionPane.showMessageDialog(null, "Registrado Exitosamente");
            
            // Limpiar inputs
            
            cbEmpleado.setSelectedIndex(0);
            this.txtUsuario.setText("");
            this.txtContraseña.setText("");
            cbNivelAcceso.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, mensajeError);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGestionarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JComboBox<String> cbNivelAcceso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblNivelAcceso;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
