/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.TransaccionControl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Irene Delgado :D  <dh16001@ues.edu.sv>
 */
public class MostrarCatalogo extends javax.swing.JFrame {

    TransaccionControl control;
    /**
     * Creates new form MostrarCatalogo
     */
    public MostrarCatalogo() throws SQLException {
        control=new TransaccionControl();
        initComponents();
        this.grupoRubros.setSelected(this.rbtnActivo.getModel(), true);
        DefaultTableModel modelo= (DefaultTableModel) this.tbCatalogo.getModel();
        String[][] catalogo=control.obtenerCuentasCatalogo(1);
        Object[] fila = new Object[modelo.getColumnCount()];
        int a=0;
        while(catalogo[a][0]!=null){ 
            fila[0]=catalogo[a][0];
            fila[1]=catalogo[a][1];
            modelo.addRow(fila);
            a++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRubros = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCatalogo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rbtnActivo = new javax.swing.JRadioButton();
        rbtnPasivo = new javax.swing.JRadioButton();
        rbtnCapital = new javax.swing.JRadioButton();
        rbtnResultado = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbCatalogo.setFont(new java.awt.Font("Vani", 0, 18)); // NOI18N
        tbCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre Cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbCatalogo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbCatalogo.setName(""); // NOI18N
        tbCatalogo.setRowHeight(22);
        jScrollPane1.setViewportView(tbCatalogo);

        jLabel1.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        jLabel1.setText("CatálogoAcopashe");

        grupoRubros.add(rbtnActivo);
        rbtnActivo.setText("Activo");
        rbtnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnActivoActionPerformed(evt);
            }
        });

        grupoRubros.add(rbtnPasivo);
        rbtnPasivo.setText("Pasivo");
        rbtnPasivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPasivoActionPerformed(evt);
            }
        });

        grupoRubros.add(rbtnCapital);
        rbtnCapital.setText("Capital");
        rbtnCapital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCapitalActionPerformed(evt);
            }
        });

        grupoRubros.add(rbtnResultado);
        rbtnResultado.setText("Resultado");
        rbtnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnResultadoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);

        grupoRubros.add(jRadioButton1);
        jRadioButton1.setText("Otras Cuentas");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnActivo)
                        .addGap(31, 31, 31)
                        .addComponent(rbtnPasivo)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnCapital)
                        .addGap(27, 27, 27)
                        .addComponent(rbtnResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1))
                    .addComponent(jLabel1))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(33, 33, 33)
                .addComponent(btnAceptar)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnActivo)
                    .addComponent(rbtnPasivo)
                    .addComponent(rbtnCapital)
                    .addComponent(rbtnResultado)
                    .addComponent(jRadioButton1))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnPasivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPasivoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tbCatalogo.getModel();
        int a = modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        modelo.removeRow(modelo.getRowCount()-1);
        } 
        String[][] catalogo;
        try {
            catalogo = control.obtenerCuentasCatalogo(2);
            Object[] fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
            } catch (SQLException ex) {
            Logger.getLogger(MostrarCatalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbtnPasivoActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tbCatalogo.getModel();
        int a = modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        modelo.removeRow(modelo.getRowCount()-1);
        } 
        String[][] catalogo;
        try {
            catalogo = control.obtenerCuentasCatalogo(6);
            Object[] fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
            catalogo = control.obtenerCuentasCatalogo(7);
            fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MostrarCatalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void rbtnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnResultadoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tbCatalogo.getModel();
        int a = modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        modelo.removeRow(modelo.getRowCount()-1);
        } 
        String[][] catalogo;
        try {
            catalogo = control.obtenerCuentasCatalogo(4);
            Object[] fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
            catalogo = control.obtenerCuentasCatalogo(5);
            fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(MostrarCatalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbtnResultadoActionPerformed

    private void rbtnCapitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCapitalActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tbCatalogo.getModel();
        int a = modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        modelo.removeRow(modelo.getRowCount()-1);
        } 
        String[][] catalogo;
        try {
            catalogo = control.obtenerCuentasCatalogo(3);
            Object[] fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
            } catch (SQLException ex) {
            Logger.getLogger(MostrarCatalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbtnCapitalActionPerformed

    private void rbtnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnActivoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tbCatalogo.getModel();
        int a = modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        modelo.removeRow(modelo.getRowCount()-1);
        } 
        String[][] catalogo;
        try {
            catalogo = control.obtenerCuentasCatalogo(1);
            Object[] fila = new Object[modelo.getColumnCount()];
            a=0;
            while(catalogo[a][0]!=null){ 
                fila[0]=catalogo[a][0];
                fila[1]=catalogo[a][1];
                modelo.addRow(fila);
                a++;
            }
            } catch (SQLException ex) {
            Logger.getLogger(MostrarCatalogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbtnActivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MostrarCatalogo().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MostrarCatalogo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup grupoRubros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnActivo;
    private javax.swing.JRadioButton rbtnCapital;
    private javax.swing.JRadioButton rbtnPasivo;
    private javax.swing.JRadioButton rbtnResultado;
    private javax.swing.JTable tbCatalogo;
    // End of variables declaration//GEN-END:variables
}
