package Vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class SeleccionTransaccionForm extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionTransaccionForm
     */
    public SeleccionTransaccionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpSeleccion = new javax.swing.ButtonGroup();
        lblSeleccionTransaccion = new javax.swing.JLabel();
        radioNormal = new javax.swing.JRadioButton();
        radioSeguro = new javax.swing.JRadioButton();
        radioAlquiler = new javax.swing.JRadioButton();
        radioPropaganda = new javax.swing.JRadioButton();
        btnInicar = new javax.swing.JButton();
        btnFinalizado = new javax.swing.JButton();
        cbTipoTransaccion = new javax.swing.JComboBox<>();
        radioPrestamoPorPagar = new javax.swing.JRadioButton();
        radioPrestamoPorCobrar = new javax.swing.JRadioButton();
        radioActivoFijoTangible = new javax.swing.JRadioButton();
        radioActivoFijoIntangible = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSeleccionTransaccion.setText("Seleccione el tipo de Transaccion a registrar:");

        btngpSeleccion.add(radioNormal);
        radioNormal.setSelected(true);
        radioNormal.setText("Normal");

        btngpSeleccion.add(radioSeguro);
        radioSeguro.setText("Seguro");

        btngpSeleccion.add(radioAlquiler);
        radioAlquiler.setText("Alquiler");

        btngpSeleccion.add(radioPropaganda);
        radioPropaganda.setText("Propaganda");

        btnInicar.setText("Iniciar registro");
        btnInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicarActionPerformed(evt);
            }
        });

        btnFinalizado.setText("Finalizado");

        cbTipoTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra", "Venta" }));

        btngpSeleccion.add(radioPrestamoPorPagar);
        radioPrestamoPorPagar.setText("Prestamo por pagar");

        btngpSeleccion.add(radioPrestamoPorCobrar);
        radioPrestamoPorCobrar.setText("Prestamo por cobrar");

        btngpSeleccion.add(radioActivoFijoTangible);
        radioActivoFijoTangible.setText("Activo fijo tangible");

        btngpSeleccion.add(radioActivoFijoIntangible);
        radioActivoFijoIntangible.setText("Activo fijo intangible");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSeleccionTransaccion)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnInicar)
                            .addGap(18, 18, 18)
                            .addComponent(btnFinalizado))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioNormal)
                            .addComponent(radioSeguro)
                            .addComponent(radioAlquiler)
                            .addComponent(radioPropaganda))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioPrestamoPorPagar)
                            .addComponent(radioActivoFijoTangible)
                            .addComponent(radioPrestamoPorCobrar)
                            .addComponent(radioActivoFijoIntangible))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblSeleccionTransaccion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNormal)
                    .addComponent(radioPrestamoPorPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSeguro)
                    .addComponent(radioPrestamoPorCobrar))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAlquiler)
                    .addComponent(radioActivoFijoTangible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPropaganda)
                    .addComponent(radioActivoFijoIntangible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(cbTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicar)
                    .addComponent(btnFinalizado))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicarActionPerformed
        try{
        //línea 1-instanciamos un objeto de la clase Formulario2.java
        String categoria = (String) cbTipoTransaccion.getSelectedItem();
        FormTransaccion verformulario2=new FormTransaccion(categoria,identificarCategoria(leerValoresRadio())); 
 
         //línea 2-hacemos visible el formulario que queremos llamar 
         verformulario2.setVisible(true);
         this.dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Algo ha fallado al iniciar una nueva\transaccion. Por favor intente mas tarde");
        }
    }//GEN-LAST:event_btnInicarActionPerformed

    //Metodo cuyo proposito es determinar los valores de los radio buttons para saber la opcion seleccionada
    private ArrayList<Boolean> leerValoresRadio()
    {
        ArrayList<Boolean> lista= new ArrayList<Boolean>();
        lista.add(radioNormal.isSelected());
        lista.add(radioSeguro.isSelected());
        lista.add(radioAlquiler.isSelected());
        lista.add(radioPropaganda.isSelected());
        lista.add(radioPrestamoPorPagar.isSelected());
        lista.add(radioPrestamoPorCobrar.isSelected());
        lista.add(radioActivoFijoTangible.isSelected());
        lista.add(radioActivoFijoIntangible.isSelected());
        return lista;
        
    }
    
    private int identificarCategoria(ArrayList<Boolean> valoresRadio)
    {
        int contador=0;
        int tipo=0;
        for(Boolean valor: valoresRadio)
        {
            if(valor)
                tipo=contador;
            
            contador++;
        }
        return tipo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionTransaccionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizado;
    private javax.swing.JButton btnInicar;
    private javax.swing.ButtonGroup btngpSeleccion;
    private javax.swing.JComboBox<String> cbTipoTransaccion;
    private javax.swing.JLabel lblSeleccionTransaccion;
    private javax.swing.JRadioButton radioActivoFijoIntangible;
    private javax.swing.JRadioButton radioActivoFijoTangible;
    private javax.swing.JRadioButton radioAlquiler;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioPrestamoPorCobrar;
    private javax.swing.JRadioButton radioPrestamoPorPagar;
    private javax.swing.JRadioButton radioPropaganda;
    private javax.swing.JRadioButton radioSeguro;
    // End of variables declaration//GEN-END:variables
}
