package Vista;

import javax.swing.JOptionPane;

public class SeleccionTransaccionForm extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionTransaccionForm
     */
    public SeleccionTransaccionForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpSeleccion = new javax.swing.ButtonGroup();
        lblSeleccionTransaccion = new javax.swing.JLabel();
        radioTransaccion = new javax.swing.JRadioButton();
        radioDGA = new javax.swing.JRadioButton();
        radioDIA = new javax.swing.JRadioButton();
        radioDAF = new javax.swing.JRadioButton();
        btnInicar = new javax.swing.JButton();
        btnFinalizado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSeleccionTransaccion.setText("Seleccione el tipo de Transaccion a registrar:");

        btngpSeleccion.add(radioTransaccion);
        radioTransaccion.setSelected(true);
        radioTransaccion.setText("Transaccion Normal");

        btngpSeleccion.add(radioDGA);
        radioDGA.setText("Detalle Gasto Adelantado");

        btngpSeleccion.add(radioDIA);
        radioDIA.setText("Detalle Intereses Acumulados");

        btngpSeleccion.add(radioDAF);
        radioDAF.setText("Detalle Activo Fijo");

        btnInicar.setText("Iniciar registro");
        btnInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicarActionPerformed(evt);
            }
        });

        btnFinalizado.setText("Finalizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDGA)
                    .addComponent(radioTransaccion)
                    .addComponent(radioDIA)
                    .addComponent(radioDAF))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblSeleccionTransaccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnInicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFinalizado)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblSeleccionTransaccion)
                .addGap(18, 18, 18)
                .addComponent(radioTransaccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioDGA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDIA)
                .addGap(3, 3, 3)
                .addComponent(radioDAF)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicar)
                    .addComponent(btnFinalizado))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicarActionPerformed
        try{
        //línea 1-instanciamos un objeto de la clase Formulario2.java
        FormTransaccion verformulario2=new FormTransaccion(); 
 
         //línea 2-hacemos visible el formulario que queremos llamar 
         verformulario2.setVisible(true);
         this.dispose();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Algo ha fallado al iniciar una nueva\transaccion. Por favor intente mas tarde");
        }
    }//GEN-LAST:event_btnInicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionTransaccionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionTransaccionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizado;
    private javax.swing.JButton btnInicar;
    private javax.swing.ButtonGroup btngpSeleccion;
    private javax.swing.JLabel lblSeleccionTransaccion;
    private javax.swing.JRadioButton radioDAF;
    private javax.swing.JRadioButton radioDGA;
    private javax.swing.JRadioButton radioDIA;
    private javax.swing.JRadioButton radioTransaccion;
    // End of variables declaration//GEN-END:variables
}
